service:
  name: sls
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs10.x

functions:
  setLocation:
    handler: handler.setLocation
  sendPhoneCode:
    handler: handler.sendPhoneCode

package:
  individually: true
